name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Render deploy hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
